services:
  - type: web
    name: ai-chatbot-backend
    env: docker
    region: Singapore (Southeast Asia)
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PORT
        value: 8000