services:
  # Backend
  - type: web
    name: ai-chatbot-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8000
      - key: AI_PROVIDER
        value: ollama
      - key: AI_MODEL
        value: llama2
    healthCheckPath: /health

  # Frontend
  - type: web
    name: ai-chatbot-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -p 3000
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-chatbot-backend
          envVarKey: RENDER_EXTERNAL_URL
